modLoader = "javafml"
loaderVersion = "[45,)"
license = "MIT"

issueTrackerURL = "https://github.com/Team-Resourceful/Resouceful-Config/issues"

[[mods]]
    modId = "resourcefulconfig"
    version = "${version}"
    displayName = "Resourcefulconfig"
    logoFile = "icon.png"
    description = "A library for creating config files for your mod across multiple platforms."

[[dependencies.resourcefulconfig]]
    modId = "forge"
    mandatory = true
    versionRange = "[45,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.resourcefulconfig]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.19.3,)"
    ordering = "NONE"
    side = "BOTH"
