modLoader = "javafml"
loaderVersion = "[43,)"
license = "MIT"

[[mods]]
    modId = "resourcefulconfig"
    version = "${version}"
    displayName = "Resourcefulconfig"
    logoFile = "icon.png"
    description = "A library for creating config files for your mod across multiple platforms."

[[dependencies.resourcefulconfig]]
    modId = "forge"
    mandatory = true
    versionRange = "[43,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.resourcefulconfig]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.19.2,1.20)"
    ordering = "NONE"
    side = "BOTH"
